services:
  presidio-analyzer:
    build: pii-detection/
    container_name: presidio-analyzer
    ports:
      - '5000:3000'
  presidio-anonymizer:
    image: ghcr.io/data-privacy-stack/presidio-anonymizer:latest
    container_name: presidio-anonymizer
    ports:
      - '5001:3000'
  redis:
    image: docker.io/library/redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

